<?php

use Drupal\node\NodeInterface;
use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResultNeutral;
use Drupal\Core\Access\AccessResultForbidden;



/**
 * Implements hook_theme() to add the template definition.
 **/
function enrope_bibliography_theme($existing, $type, $theme, $path)
{
  return array(
    'enrope_bibliography_disclaimer_block_template' => array(
      'variables' => array(),
    ),


  );
}
