<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
function enrope_group_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Adding custom validation for group join form
  if ($form_id == 'group_content_isp_group_type-group_membership_group-join_form') {
    $form['actions']['submit']['#submit'][] = '_custom_form_submit';
  }
}
function _custom_form_submit(&$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  //Redirect to group nodes after join
  $group_content = $form_state->getFormObject()->getEntity();
  $group = $group_content->getGroup();

  $url = url::fromUserInput('/group/' . $group->id() . '/nodes');
  $form_state->setRedirectUrl($url);
}

