<?php

/**
 * Implements hook_theme() to add the template definition.
 **/
function enrope_timeline_map_theme($existing, $type, $theme, $path) {
  return array(
    'enrope_timeline_template' => array(
      'variables' => array(),
    ),
    'enrope_map_block_template' => array(
      'variables' => array(),
    ),


  );

//  return array(
//    'enrope_timeline_template' => array(
//      'variables' => array('test_var' => NULL),
//    ),
//  );
}